name        : lander
version     : 1.3
release     : 1
source      :
    - https://github.com/kevinarefunny/Lander/archive/1.3.tar.gz : 7a126abdbfe10c98cfb5accd1df911b136f59629b6479de9e737ca84b3ec7f74
license     :
    - GPL-3.0
component   : games.arcade
summary     : CLI Top-Down Space Shooter
description : |
    * z moves left
    * x shoots
    * c moves right
build      : |
    %make
install    : |
    %make_install
